#define SECRET_MQTT_USENAME "LRE0LSQdKCUhAh4qJSERHTM"
#define SECRET_MQTT_CLIENT_ID "LRE0LSQdKCUhAh4qJSERHTM"
#define SECRET_MQTT_PASSWORD "osYMYsUu2jIzS6E0wZfttwxT"

#define SECRET_WIFI_NAME "Phong 1"
#define SECRET_WIFI_PASSWORD "66662626"
#define CHANNEL_ID "3084270"